//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FC.Auth.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FC.Auth.WebAPI.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bairro é obrigatório..
        /// </summary>
        public static string AlterarUsuario_BairroObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.BairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP está em formato inválido..
        /// </summary>
        public static string AlterarUsuario_CepInvalido {
            get {
                return ResourceManager.GetString("AlterarUsuario.CepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é obrigatório..
        /// </summary>
        public static string AlterarUsuario_CepObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.CepObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cidade é obrigatória..
        /// </summary>
        public static string AlterarUsuario_CidadeObrigatoria {
            get {
                return ResourceManager.GetString("AlterarUsuario.CidadeObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O DDD deve conter exatamente 2 dígitos..
        /// </summary>
        public static string AlterarUsuario_DddInvalido {
            get {
                return ResourceManager.GetString("AlterarUsuario.DddInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O DDD é obrigatório..
        /// </summary>
        public static string AlterarUsuario_DddObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.DddObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado é obrigatório..
        /// </summary>
        public static string AlterarUsuario_EstadoObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.EstadoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O id do usuário é obrigatório..
        /// </summary>
        public static string AlterarUsuario_IdObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.IdObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O logradouro é obrigatório..
        /// </summary>
        public static string AlterarUsuario_LogradouroObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.LogradouroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O primeiro nome deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string AlterarUsuario_NomeInvalido {
            get {
                return ResourceManager.GetString("AlterarUsuario.NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O primeiro nome é obrigatório..
        /// </summary>
        public static string AlterarUsuario_NomeObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número é obrigatório..
        /// </summary>
        public static string AlterarUsuario_NumeroObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.NumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone deve conter entre 8 e 9 dígitos..
        /// </summary>
        public static string AlterarUsuario_NumeroTelefoneInvalido {
            get {
                return ResourceManager.GetString("AlterarUsuario.NumeroTelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número de telefone é obrigatório..
        /// </summary>
        public static string AlterarUsuario_NumeroTelefoneObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.NumeroTelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome deve ter no mínimo 2 caracteres..
        /// </summary>
        public static string AlterarUsuario_SobrenomeInvalido {
            get {
                return ResourceManager.GetString("AlterarUsuario.SobrenomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sobrenome é obrigatório..
        /// </summary>
        public static string AlterarUsuario_SobrenomeObrigatorio {
            get {
                return ResourceManager.GetString("AlterarUsuario.SobrenomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é inválido..
        /// </summary>
        public static string CriarUsuario_EmailInvalido {
            get {
                return ResourceManager.GetString("CriarUsuario.EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string CriarUsuario_EmailObrigatorio {
            get {
                return ResourceManager.GetString("CriarUsuario.EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome deve ter no mínimo 3 caracteres..
        /// </summary>
        public static string CriarUsuario_NomeInvalido {
            get {
                return ResourceManager.GetString("CriarUsuario.NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string CriarUsuario_NomeObrigatorio {
            get {
                return ResourceManager.GetString("CriarUsuario.NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um caractere especial. .
        /// </summary>
        public static string CriarUsuario_SenhaCaracter {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaCaracter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha precisa estar criptografada..
        /// </summary>
        public static string CriarUsuario_SenhaInvalida {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos uma letra maiúscula..
        /// </summary>
        public static string CriarUsuario_SenhaLetraMaiuscula {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaLetraMaiuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos uma letra minúscula..
        /// </summary>
        public static string CriarUsuario_SenhaLetraMinuscula {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaLetraMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter pelo menos um número..
        /// </summary>
        public static string CriarUsuario_SenhaNumero {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string CriarUsuario_SenhaObrigatoria {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no máximo 20 caracteres..
        /// </summary>
        public static string CriarUsuario_SenhaTamanhoCaracteres {
            get {
                return ResourceManager.GetString("CriarUsuario.SenhaTamanhoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado..
        /// </summary>
        public static string Error_GenericError {
            get {
                return ResourceManager.GetString("Error.GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID da rota difere do corpo da requisição..
        /// </summary>
        public static string Error_RequestBodyIdMismatch {
            get {
                return ResourceManager.GetString("Error.RequestBodyIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O recurso não foi encontrado..
        /// </summary>
        public static string Error_ResourceNotFound {
            get {
                return ResourceManager.GetString("Error.ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de validação..
        /// </summary>
        public static string Error_ValidationFailed {
            get {
                return ResourceManager.GetString("Error.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credencial inválida..
        /// </summary>
        public static string Login_CredenciaisInvalidas {
            get {
                return ResourceManager.GetString("Login.CredenciaisInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string Login_EmailObrigatorio {
            get {
                return ResourceManager.GetString("Login.EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha é obrigatória..
        /// </summary>
        public static string Login_SenhaObrigatoria {
            get {
                return ResourceManager.GetString("Login.SenhaObrigatoria", resourceCulture);
            }
        }
    }
}
