<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="19.225.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\buildingblocks\FC.BuildingBlocks.Domain\FC.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\FC.Auth.Domain\FC.Auth.Domain.csproj" />
  </ItemGroup>

</Project>
